var map = new Datamap({
    	element: document.getElementById('container'),
    	geographyConfig: {
	    	highlightBorderColor: '#bada55',
	      	popupTemplate: function(geography, data) { //this function should just return a string
		      	if(data.influence && !data.influenceby) return ['<div class="hoverinfo"><strong>' + geography.properties.name + '</strong><br>Result:<br>' + data.influence + '</div>'].join('');
		      	else if(!data.influence && data.influenceby) return ['<div class="hoverinfo"><strong>' + geography.properties.name + '</strong><br>Influenced by:<br>' + data.influenceby + '</div>'].join('');
		      	else if(data.influence && data.influenceby) return ['<div class="hoverinfo"><strong>' + geography.properties.name + '</strong><br><u>Influenced by:</u><br>' + data.influenceby +  '<br><u>Result:</u><br>' + data.influence +'</div>'].join('');
		      	else
		      		return ['<div class="hoverinfo"><strong>' + geography.properties.name + '</strong></div>'].join('');
       	 	},
   		},
    	fills: {
            VISITED: 'blue',
            MELANESIA: 'purple',
            MICRONESIA: 'yellow',
            POLYNESIA: 'pink',
            UNKNOWN: 'green',
            defaultFill: 'green'
        },
        data: {
        	
            ABW:{}, 
			AFG:{},
			AGO:{},
			AIA:{},
			ALA:{},
			ALB:{},
			AND:{},
			ARE:{},
			ARG:{},
			ARM:{},
			ASM:{},
			ATA:{},
			ATF:{},
			ATG:{},
			AUT:{},
			AZE:{},
			BDI:{},
			BEL:{},
			BEN:{},
			BES:{},
			BFA:{},
			BGD:{},
			BGR:{},
			BHR:{},
			BHS:{},
			BIH:{},
			BLM:{},
			BLR:{},
			BLZ:{},
			BMU:{},
			BOL:{},
			BRA:{},
			BRB:{},
			BRN:{},
			BTN:{},
			BVT:{},
			BWA:{},
			CAF:{},
			CAN:{},
			CCK:{},
			CHE:{},
			CHL:{},
			CHN:{},
			CIV:{},
			CMR:{},
			COD:{},
			COG:{},
			COK:{},
			COL:{},
			COM:{},
			CPV:{},
			CRI:{},
			CUW:{},
			CXR:{},
			CYM:{},
			CYP:{},
			CZE:{},
			DEU:{},
			DJI:{},
			DMA:{},
			DNK:{},
			DZA:{},
			ECU:{},
			EGY:{},
			ERI:{},
			ESH:{},
			EST:{},
			ETH:{},
			FIN:{},
			FJI:{},
			FLK:{},
			FRO:{},
			FSM:{},
			GAB:{},
			GBR:{},
			GEO:{},
			GGY:{},
			GHA:{},
			GIB:{},
			GIN:{},
			GLP:{},
			GMB:{},
			GNB:{},
			GNQ:{},
			GRC:{},
			GRD:{},
			GRL:{},
			GTM:{},
			GUF:{},
			GUM:{},
			GUY:{},
			HKG:{},
			HMD:{},
			HND:{},
			HRV:{},
			HTI:{},
			HUN:{},
			IDN:{},
			IMN:{},
			IND:{},
			IOT:{},
			IRL:{},
			IRN:{},
			IRQ:{},
			ISL:{},
			ISR:{},
			ITA:{},
			JAM:{},
			JEY:{},
			JOR:{},
			JPN:{},
			KAZ:{},
			KEN:{},
			KGZ:{},
			KHM:{},
			KIR:{},
			KNA:{},
			KOR:{},
			KWT:{},
			LAO:{},
			LBN:{},
			LBR:{},
			LBY:{},
			LCA:{},
			LIE:{},
			LKA:{},
			LSO:{},
			LTU:{},
			LUX:{},
			LVA:{},
			MAC:{},
			MAF:{},
			MAR:{},
			MCO:{},
			MDA:{},
			MDG:{},
			MDV:{},
			MEX:{},
			MHL:{},
			MKD:{},
			MLI:{},
			MLT:{},
			MMR:{},
			MNE:{},
			MNG:{},
			MNP:{},
			MOZ:{},
			MRT:{},
			MSR:{},
			MTQ:{},
			MUS:{},
			MWI:{},
			MYS:{},
			MYT:{},
			NAM:{},
			NCL:{},
			NER:{},
			NFK:{},
			NGA:{},
			NIC:{},
			NIU:{},
			NLD:{},
			NOR:{},
			NPL:{},
			NRU:{},
			NZL:{},
			OMN:{},
			PAK:{},
			PAN:{},
			PCN:{},
			PER:{},
			PHL:{},
			PLW:{},
			POL:{},
			PRI:{},
			PRK:{},
			PRT:{},
			PRY:{},
			PSE:{},
			PYF:{},
			QAT:{},
			REU:{},
			ROU:{},
			RUS:{},
			RWA:{},
			SAU:{},
			SDN:{},
			SEN:{},
			SGP:{},
			SGS:{},
			SHN:{},
			SJM:{},
			SLB:{},
			SLE:{},
			SLV:{},
			SMR:{},
			SOM:{},
			SPM:{},
			SRB:{},
			STP:{},
			SUR:{},
			SVK:{},
			SVN:{},
			SWE:{},
			SWZ:{},
			SXM:{},
			SYC:{},
			SYR:{},
			TCA:{},
			TCD:{},
			TGO:{},
			THA:{},
			TJK:{},
			TKL:{},
			TKM:{},
			TLS:{},
			TON:{},
			TTO:{},
			TUN:{},
			TUR:{},
			TUV:{},
			TWN:{},
			TZA:{},
			UGA:{},
			UKR:{},
			UMI:{},
			URY:{},
			UZB:{},
			VAT:{},
			VCT:{},
			VEN:{},
			VGB:{},
			VIR:{},
			VNM:{},
			VUT:{},
			WLF:{},
			WSM:{},
			YEM:{},
			ZAF:{},
			ZMB:{},
			ZWE:{},
			PNG: {},
            USA: {
            },
            AUS: {
            },
            ESP: {
            },
			CUB: {
            },
            FRA: {
            },
            GER: {
            },
            DOM: {

            },

        }
    });

    map.arc([
    	{
			//GBR
			origin:{
				latitude: 53.415,
		    	longitude: -1.1619,
			},
			//polynesia
			destination:{
				latitude: 1.415,
		    	longitude: 166.1619,
			}
		},
		{
			//USA
			origin:{
				latitude: 40.4333,
				longitude: -100
			},
			//poly
			destination:{
				latitude: 1.415,
		    	longitude: 166.1619,
			}
		},
		{
			//france
			origin:{
				latitude: 47.4333,
				longitude: 5
			},
			//cuba
			destination:{
				latitude: 20,
				longitude: -75
			}
		}
],  {strokeWidth: 2, arcSharpness: 1.4});

	map.bubbles([
		{
		    name: 'Melanesia',
		    radius: 5,
		    fillKey: 'MELANESIA',
		    latitude: 10.415,
		    longitude: 145.1619
		},
		{
		    name: 'Micronesia',
		    radius: 5,
		    fillKey: 'MICRONESIA',
		    latitude: -7.415,
		    longitude: 145.1619
		},
	{
	    name: 'Polynesia',
	    radius: 35,
	    fillKey: 'VISITED',
	    latitude: 1.415,
	    longitude: 166.1619,
	    influenceby: 'Great Britain and the USA',
	    influence: '-Protestant hymns and strophic form which inspired himenes'
	}],
	{
		popupTemplate: function(geo, data) {
			if(data.influenceby){
				return '<div class="hoverinfo"><strong>' + data.name + '</strong><br><u>Influence by:</u><br>' + data.influenceby + '<br><u>Result:</u><br> ' + data.influence + '</div>';
			}
			else{
				return '<div class="hoverinfo"><strong>' + data.name + '</strong></div>';
			}
		}
	});

